apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: default
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa
  namespace: default
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytic-sa
  namespace: default